"Country" integer,
"Admin1" VARCHAR (3),
"SubDiv" VARCHAR (3),
"Year" integer,
"List" VARCHAR (3),
"Cause" VARCHAR (4),
"Sex" integer,
"Frmat" VARCHAR (2),
"IM_Frmat" VARCHAR (2),
"Deaths1" integer,
"Deaths2" integer,
"Deaths3" integer,
"Deaths4" integer,
"Deaths5" integer,
"Deaths6" integer,
"Deaths7" integer,
"Deaths8" integer,
"Deaths9" integer,
"Deaths10" integer,
"Deaths11" integer,
"Deaths12" integer,
"Deaths13" integer,
"Deaths14" integer,
"Deaths15" integer,
"Deaths16" integer,
"Deaths17" integer,
"Deaths18" integer,
"Deaths19" integer,
"Deaths20" integer,
"Deaths21" integer,
"Deaths22" integer,
"Deaths23" integer,
"Deaths24" integer,
"Deaths25" integer,
"Deaths26" integer,
"IM_Deaths1" integer,
"IM_Deaths2" integer,
"IM_Deaths3" integer,
"IM_Deaths4" integer