"Country" integer,
"Admin1" VARCHAR (3),
"SubDiv" VARCHAR (3),
"Year" integer,
"Sex" integer,
"Frmat" VARCHAR (2),
"Pop1" numeric,
"Pop2" numeric,
"Pop3" numeric,
"Pop4" numeric,
"Pop5" numeric,
"Pop6" numeric,
"Pop7" numeric,
"Pop8" numeric,
"Pop9" numeric,
"Pop10" numeric,
"Pop11" numeric,
"Pop12" numeric,
"Pop13" numeric,
"Pop14" numeric,
"Pop15" numeric,
"Pop16" numeric,
"Pop17" numeric,
"Pop18" numeric,
"Pop19" numeric,
"Pop20" numeric,
"Pop21" numeric,
"Pop22" numeric,
"Pop23" numeric,
"Pop24" numeric,
"Pop25" numeric,
"Pop26" numeric,
"Lb" integer